### PR TITLE
fix: make manual mining produce non-empty blocks

### LINKED ISSUE #404: fix: `evm_mine` should produce non-empty blocks when it can
Currently `evm_mine` always produces an empty block without looking at the mempool. This shouldn't be the case - we want `evm_mine` to take whatever it can from the mempool and produce a block that way; sort of how immediate sealing mode works in https://github.com/matter-labs/era-test-node/pull/392.

### PR DESCRIPTION
**Pull request by itegulov**
# What :computer: 
* Minor refactorings to reduce boilerplate and unnecessary locking
* Makes all manual mining methods take transactions from the mempool when they can

Closes #404 

# Why :hand:
Correct behavior expected by users

### CODE REVIEW

File: src/node/in_memory_ext.rs [hunk 1]
```diff
@@ -137,70 +142,61 @@ impl<S: ForkSource + std::fmt::Debug + Clone + Send + Sync + 'static> InMemoryNo
...
-                    })
-                    .map_err(|err| anyhow!("{}", err))
-            })
+            // remove all snapshots following the index and use the first snapshot for restore
+            let selected_snapshot = snapshots
+                .drain(snapshot_id_index..)
+                .next()
+                .expect("unexpected failure, value must exist");
+
+            tracing::info!("Reverting node to snapshot '{snapshot_id:?}'");
```
Comment (dutterbutter) [inline src/node/in_memory_ext.rs:160]: Throughout snapshot / mining modes we are using `tracing::info!`, do we want these to be written out by default? I know we want to move away from `tracing::info` all together but curious your thoughts on outputting this information.

**Review by dutterbutter — DISMISSED** [review]
lgtm

**Review by dutterbutter — APPROVED** [review]

File: src/node/in_memory_ext.rs (hunk 1 above)
Comment (itegulov) [reply src/node/in_memory_ext.rs:202]: Yeah I am not adding new `tracing::info`, this line existed before this PR and I think we should refactor logging in a separate PR to reduce the noise.

Generally speaking IMO we should only use `tracing::trace` or `tracing::debug`.
